# Generated by Django 6.0.3 on 2026-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('rollNo', models.CharField(max_length=50)),
                ('physics', models.CharField(max_length=50)),
                ('chemistry', models.CharField(max_length=50)),
                ('maths', models.DateField(max_length=50)),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fristName',
            new_name='firstName',
        ),
    ]
