# Generated by Django 6.0.3 on 2026-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_marksheet_rename_fristname_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='chemistry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='maths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='physics',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='rollNo',
            field=models.IntegerField(),
        ),
    ]
